puts "Create admin ..."
admin = User.create first_name: 'admin', last_name: 'admin', email: 'admin@petmode.com', login: 'admin', password: 'secret', password_confirmation: 'secret', country_id: 1, city: 'City'
admin.roles << Role.admin

puts "Create users ..."
50.times do |i|
  user = User.create first_name: "user_#{ i }", last_name: "user_#{ i }", email: "user_#{ i }@petmode.com", login: "user_#{ i }", password: 'secret', password_confirmation: 'secret', country_id: 1, city: 'City'
  user.roles << Role.user
end

puts "Create cat breeds ..."

Breed.create family: 'cat', title_en: 'Abyssinian', title_ru: 'Абиссинская'
Breed.create family: 'cat', title_en: 'Australian_Mist', title_ru: 'Австралийская дымчатая'
Breed.create family: 'cat', title_en: 'Australian_Tiffanie', title_ru: 'Австралийская тиффани'
Breed.create family: 'cat', title_en: 'Asian_Longhair', title_ru: 'Азиатская длинношерстная (Тиффани)'
Breed.create family: 'cat', title_en: 'Asian_Smoke', title_ru: 'Азиатская дымчатая'
Breed.create family: 'cat', title_en: 'Asian_Shorthair', title_ru: 'Азиатская короткошерстная'
Breed.create family: 'cat', title_en: 'Asian_Tabby', title_ru: 'Азиатская табби'
Breed.create family: 'cat', title_en: 'American_Wirehair', title_ru: 'Американская жесткошерстная'
Breed.create family: 'cat', title_en: 'American_Ringtail', title_ru: 'Американская кольцехвостая'
Breed.create family: 'cat', title_en: 'American_Shorthair', title_ru: 'Американская короткошерстная'
Breed.create family: 'cat', title_en: 'American_Bobtail', title_ru: 'Американский бобтейл'
Breed.create family: 'cat', title_en: 'American_Curl', title_ru: 'Американский кёрл'
Breed.create family: 'cat', title_en: 'Anatoli', title_ru: 'Анатолийская'
Breed.create family: 'cat', title_en: 'Arabian_Mau', title_ru: 'Аравийский мау'
Breed.create family: 'cat', title_en: 'Balinese', title_ru: 'Балинезийская (балинез)'
Breed.create family: 'cat', title_en: 'Bengal', title_ru: 'Бенгальская короткошерстная (Бенгал)'
Breed.create family: 'cat', title_en: 'Birman', title_ru: 'Бирманская'
Breed.create family: 'cat', title_en: 'Bohemia_Rex', title_ru: 'Богемский рекс'
Breed.create family: 'cat', title_en: 'Bombay', title_ru: 'Бомбейская (Бомбей)'
Breed.create family: 'cat', title_en: 'Brazilian_Shorthair', title_ru: 'Бразильская короткошерстная'
Breed.create family: 'cat', title_en: 'Bristol', title_ru: 'Бристоль'
Breed.create family: 'cat', title_en: 'British_Longhair', title_ru: 'Британская длинношерстная'
Breed.create family: 'cat', title_en: 'British_Shorthair', title_ru: 'Британская короткошерстная'
Breed.create family: 'cat', title_en: 'Burmese', title_ru: 'Бурмезская короткошерстная (бурма)'
Breed.create family: 'cat', title_en: 'Burmilla', title_ru: 'Бурмилла'
Breed.create family: 'cat', title_en: 'Havana_Brown', title_ru: 'Гавана браун'
Breed.create family: 'cat', title_en: 'German_Rex', title_ru: 'Герман рекс (Немецкий рекс)'
Breed.create family: 'cat', title_en: 'Devon_Rex', title_ru: 'Девон-рекс'
Breed.create family: 'cat', title_en: 'Domestic_cat', title_ru: 'Домашняя кошка'
Breed.create family: 'cat', title_en: 'Don_Sphynx', title_ru: 'Донской сфинкс'
Breed.create family: 'cat', title_en: 'European_SH', title_ru: 'Европейская КШ (Кельтская)'
Breed.create family: 'cat', title_en: 'Egyptian_Mau', title_ru: 'Египетская мау'
Breed.create family: 'cat', title_en: 'Foreign_White', title_ru: 'Иностранная Белая'
Breed.create family: 'cat', title_en: 'York_Chocolate', title_ru: 'Йорк (Йоркская шоколадная)'
Breed.create family: 'cat', title_en: 'California_Spangled', title_ru: 'Калифорнийская сияющая'
Breed.create family: 'cat', title_en: 'Kanaani', title_ru: 'Канаани (Ханаани)'
Breed.create family: 'cat', title_en: 'Karelian_Bobtail', title_ru: 'Карельский бобтейл'
Breed.create family: 'cat', title_en: 'Cymric', title_ru: 'Кимрик (длинношерстный манкс)'
Breed.create family: 'cat', title_en: 'Chinese_Li_Hua', title_ru: 'Китайская Ли Hua'
Breed.create family: 'cat', title_en: 'Korat', title_ru: 'Корат'
Breed.create family: 'cat', title_en: 'Cornish_Rex', title_ru: 'Корниш-рекс'
Breed.create family: 'cat', title_en: 'Kurilian_Bobtail', title_ru: 'Курильский бобтейл'
Breed.create family: 'cat', title_en: 'LaPerm', title_ru: 'Лаперм'
Breed.create family: 'cat', title_en: 'Mandalay', title_ru: 'Мандалай (Мандалэй)'
Breed.create family: 'cat', title_en: 'Munchkin', title_ru: 'Манчкин'
Breed.create family: 'cat', title_en: 'Maine_Coon', title_ru: 'Мейн-кун'
Breed.create family: 'cat', title_en: 'Mekong_Bobtail', title_ru: 'Меконгский бобтейл'
Breed.create family: 'cat', title_en: 'Manx', title_ru: 'Мэнская безхвостая (Манкс)'
Breed.create family: 'cat', title_en: 'Neva_Masquerade', title_ru: 'Невская маскарадная'
Breed.create family: 'cat', title_en: 'Nebelung', title_ru: 'Нибелунг'
Breed.create family: 'cat', title_en: 'Norwegian_Forest', title_ru: 'Норвежская лесная'
Breed.create family: 'cat', title_en: 'Oriental_Shorthair', title_ru: 'Ориентальная короткошерстная'
Breed.create family: 'cat', title_en: 'Ojos_Azules', title_ru: 'Охос Азулес'
Breed.create family: 'cat', title_en: 'Ocicat', title_ru: 'Оцикет'
Breed.create family: 'cat', title_en: 'Persian', title_ru: 'Персидская'
Breed.create family: 'cat', title_en: 'Peterbald', title_ru: 'Петерболд (Петербургский сфинкс)'
Breed.create family: 'cat', title_en: 'Pixiebob', title_ru: 'Пиксибоб'
Breed.create family: 'cat', title_en: 'Poodle_Cat', title_ru: 'Пуделькэт'
Breed.create family: 'cat', title_en: 'Ragamuffin', title_ru: 'Рагамаффин'
Breed.create family: 'cat', title_en: 'Russian_Blue', title_ru: 'Русская голубая'
Breed.create family: 'cat', title_en: 'Ragdoll', title_ru: 'Рэгдолл'
Breed.create family: 'cat', title_en: 'Savannah', title_ru: 'Саванна'
Breed.create family: 'cat', title_en: 'Selkirk_Rex', title_ru: 'Селкирк-рекс'
Breed.create family: 'cat', title_en: 'Serengeti', title_ru: 'Серенгети'
Breed.create family: 'cat', title_en: 'Siamese', title_ru: 'Сиамская'
Breed.create family: 'cat', title_en: 'Siberian', title_ru: 'Сибирская'
Breed.create family: 'cat', title_en: 'Singapura', title_ru: 'Сингапура'
Breed.create family: 'cat', title_en: 'Scottish_Straight', title_ru: 'Скоттиш страйт'
Breed.create family: 'cat', title_en: 'Scottish_Fold_LH', title_ru: 'Скоттиш фолд  длинношерстный (Хайленд-фолд)'
Breed.create family: 'cat', title_en: 'Scottish_Fold_SH', title_ru: 'Скоттиш фолд  короткошерстный'
Breed.create family: 'cat', title_en: 'Snowshoe', title_ru: 'Сноу-шу'
Breed.create family: 'cat', title_en: 'Somali', title_ru: 'Сомали (Абиссинская ДШ)'
Breed.create family: 'cat', title_en: 'Sokoke', title_ru: 'Соукок'
Breed.create family: 'cat', title_en: 'Sphynx', title_ru: 'Сфинкс (Канадский сфинкс)'
Breed.create family: 'cat', title_en: 'Thai', title_ru: 'Тайская'
Breed.create family: 'cat', title_en: 'Tiffany', title_ru: 'Тиффани'
Breed.create family: 'cat', title_en: 'Toy-Bobtail', title_ru: 'Тойбоб, Скиф-тай-той-Дон'
Breed.create family: 'cat', title_en: 'Toyger', title_ru: 'Тойгер'
Breed.create family: 'cat', title_en: 'Tonkinese', title_ru: 'Тонкинская'
Breed.create family: 'cat', title_en: 'Turkish_Angora', title_ru: 'Турецкая ангора'
Breed.create family: 'cat', title_en: 'Turkish_Van', title_ru: 'Турецкий ван'
Breed.create family: 'cat', title_en: 'Ural_Rex', title_ru: 'Уральский рекс'
Breed.create family: 'cat', title_en: 'Ussuri', title_ru: 'Уссурийская КШ (Уссури)'
Breed.create family: 'cat', title_en: 'Ceylon', title_ru: 'Цейлонская'
Breed.create family: 'cat', title_en: 'Chausie', title_ru: 'Чаузи (Шаузи, Хаузи)'
Breed.create family: 'cat', title_en: 'Chartreux', title_ru: 'Шартрез'
Breed.create family: 'cat', title_en: 'Exotic_Shorthair', title_ru: 'Экзотическая короткошерстная'
Breed.create family: 'cat', title_en: 'Javanese', title_ru: 'Яванская (яванез)'
Breed.create family: 'cat', title_en: 'Japanese_Bobtail', title_ru: 'Японский бобтейл'

puts "Create dog breeds ..."

Breed.create family: 'dog', title_en: 'Australian_Shepherd', title_ru: 'Австралийская овчарка'
Breed.create family: 'dog', title_en: 'Queensland_Heeler', title_ru: 'Австралийская пастушья собака'
Breed.create family: 'dog', title_en: 'Australian_Cattle_Dog', title_ru: 'Австралийская пастушья собака / Голубой хилер'
Breed.create family: 'dog', title_en: 'Australian_Kelpie', title_ru: 'Австралийский келпи'
Breed.create family: 'dog', title_en: 'Aussiedoodle', title_ru: 'Австралийский пудель'
Breed.create family: 'dog', title_en: 'Australian_Terrier', title_ru: 'Австралийский терьер'
Breed.create family: 'dog', title_en: 'Silky_Terrier', title_ru: 'Австралийский шелковистый терьер '
Breed.create family: 'dog', title_en: 'Azawakh', title_ru: 'Азавак'
Breed.create family: 'dog', title_en: 'Akbash', title_ru: 'Акбаш'
Breed.create family: 'dog', title_en: 'Akita', title_ru: 'Акита'
Breed.create family: 'dog', title_en: 'Alapaha_Blue_Blood_Bulldog', title_ru: 'Алапахский чистокровный бульдог / альпаха'
Breed.create family: 'dog', title_en: 'Alaskan_Klee_Kai', title_ru: 'Аляскинский Кли Кай'
Breed.create family: 'dog', title_en: 'Alaskan_Malamute', title_ru: 'Аляскинский маламут'
Breed.create family: 'dog', title_en: 'American_English_Coonhound', title_ru: 'Американский английский кунхаунд'
Breed.create family: 'dog', title_en: 'American_Bulldog', title_ru: 'Американский бульдог'
Breed.create family: 'dog', title_en: 'American_Water_Spaniel', title_ru: 'Американский водяной спаниель'
Breed.create family: 'dog', title_en: 'American_Hairless_Terrier', title_ru: 'Американский голый терьер'
Breed.create family: 'dog', title_en: 'American_Pit_Bull_Terrier', title_ru: 'Американский Пит Бультерьер'
Breed.create family: 'dog', title_en: 'American_Staffordshire_Terrier', title_ru: 'Американский стаффордширский терьер'
Breed.create family: 'dog', title_en: 'American_Foxhound', title_ru: 'Американский фоксхаунд'
Breed.create family: 'dog', title_en: 'American_Eskimo_Dog', title_ru: 'Американский эскимосский шпиц'
Breed.create family: 'dog', title_en: 'Anatolian_Shepherd', title_ru: 'Анатолийская пастушья собака'
Breed.create family: 'dog', title_en: 'English_Coonhound', title_ru: 'Английская Енотовая Гончая'
Breed.create family: 'dog', title_en: 'English_Shepherd', title_ru: 'Английская овчарка'
Breed.create family: 'dog', title_en: 'English_Boodle', title_ru: 'Английский будель'
Breed.create family: 'dog', title_en: 'English_Bulldog', title_ru: 'Английский Бульдог'
Breed.create family: 'dog', title_en: 'English_Cocker_Spaniel', title_ru: 'Английский кокер спаниель'
Breed.create family: 'dog', title_en: 'English_Pointer', title_ru: 'Английский пойнтер'
Breed.create family: 'dog', title_en: 'English_Setter', title_ru: 'Английский сеттер'
Breed.create family: 'dog', title_en: 'English_Springer_Spaniel', title_ru: 'Английский спрингер спаниель'
Breed.create family: 'dog', title_en: 'English_Toy_Spaniel', title_ru: 'Английский той-спаниель'
Breed.create family: 'dog', title_en: 'Appenzell_Mountain_Dog', title_ru: 'Аппенцелльская горная собака '
Breed.create family: 'dog', title_en: 'Argentine_Dogo', title_ru: 'Аргентинский дог'
Breed.create family: 'dog', title_en: 'Afghan_Hound', title_ru: 'Афган '
Breed.create family: 'dog', title_en: 'Affenpinscher', title_ru: 'Аффенпинчер '
Breed.create family: 'dog', title_en: 'Basenji', title_ru: 'Басенджи'
Breed.create family: 'dog', title_en: 'Basset_Hound', title_ru: 'Бассет-хаунд'
Breed.create family: 'dog', title_en: 'Bedlington_Terrier', title_ru: 'Бедлингтон-терьер'
Breed.create family: 'dog', title_en: 'Belgian_Sheepdog', title_ru: 'Бельгийская овчарка'
Breed.create family: 'dog', title_en: 'Belgian_Shepherd_Laekenois', title_ru: 'Бельгийская овчарка Лакенуа'
Breed.create family: 'dog', title_en: 'Belgian_Shepherd_Malinois', title_ru: 'Бельгийская овчарка Малинуа'
Breed.create family: 'dog', title_en: 'Belgian_Shepherd_Tervuren', title_ru: 'Бельгийская овчарка Тервюрен'
Breed.create family: 'dog', title_en: 'Bergamasco', title_ru: 'Бергамская овчарка'
Breed.create family: 'dog', title_en: 'Bernese_Mountain_Dog', title_ru: 'Бернский зенненхунд / Бернская горная пастушья собака'
Breed.create family: 'dog', title_en: 'Beaglier', title_ru: 'Биглие '
Breed.create family: 'dog', title_en: 'Beagle', title_ru: 'Бигль'
Breed.create family: 'dog', title_en: 'Bichon_Frise', title_ru: 'Бишон фризе '
Breed.create family: 'dog', title_en: 'Bichpoo', title_ru: 'Бишпу '
Breed.create family: 'dog', title_en: 'Bloodhound', title_ru: 'Бладхаунд'
Breed.create family: 'dog', title_en: 'Boykin_Spaniel', title_ru: 'Бойкин Спаниель'
Breed.create family: 'dog', title_en: 'Boxerdoodle', title_ru: 'Бокседудл '
Breed.create family: 'dog', title_en: 'Boxer', title_ru: 'Боксер'
Breed.create family: 'dog', title_en: 'Bolognese', title_ru: 'Болоньез'
Breed.create family: 'dog', title_en: 'Greater_Swiss_Mountain_Dog', title_ru: 'Большой Швейцарский Зенненхунд / Большая швейцарская пастушья собака'
Breed.create family: 'dog', title_en: 'Border_Collie', title_ru: 'Бордер Колли'
Breed.create family: 'dog', title_en: 'Border_Terrier', title_ru: 'Бордер Терьер'
Breed.create family: 'dog', title_en: 'Dogue_De_Bordeaux', title_ru: 'Бордоский дог '
Breed.create family: 'dog', title_en: 'Borzoi', title_ru: 'Борзая '
Breed.create family: 'dog', title_en: 'Bearded_Collie', title_ru: 'Бородатый Колли'
Breed.create family: 'dog', title_en: 'Beauceron', title_ru: 'Босерон'
Breed.create family: 'dog', title_en: 'Boston_Terrier', title_ru: 'Бостон Терьер'
Breed.create family: 'dog', title_en: 'Bracco_Italiano', title_ru: 'Бракко Итальяно '
Breed.create family: 'dog', title_en: 'Brittany_Spaniel', title_ru: 'Бретонский спаниель '
Breed.create family: 'dog', title_en: 'Briard', title_ru: 'Бриар'
Breed.create family: 'dog', title_en: 'Brussels_Griffon', title_ru: 'Брюссельский гриффон'
Breed.create family: 'dog', title_en: 'Bouvier_Des_Flandres', title_ru: 'Бувье Де Фландр'
Breed.create family: 'dog', title_en: 'Bulldog', title_ru: 'Бульдог'
Breed.create family: 'dog', title_en: 'Bullmastiff', title_ru: 'Бульмастиф'
Breed.create family: 'dog', title_en: 'Bull_Terrier', title_ru: 'Бультерьер'
Breed.create family: 'dog', title_en: 'Briquet_Griffon_Vendeen', title_ru: 'Вандейский брикет-гриффон'
Breed.create family: 'dog', title_en: 'Weimaraner', title_ru: 'Веймаранер'
Breed.create family: 'dog', title_en: 'Weimardoodle', title_ru: 'Веймардудль '
Breed.create family: 'dog', title_en: 'Welsh_Corgi_Cardigan', title_ru: 'Вельш Корги Кардиган'
Breed.create family: 'dog', title_en: 'Welsh_Corgi_Pembroke', title_ru: 'Вельш Корги Пемброк'
Breed.create family: 'dog', title_en: 'Welsh_Springer_Spaniel', title_ru: 'Вельш спрингер спаниель'
Breed.create family: 'dog', title_en: 'Welsh_Terrier', title_ru: 'Вельштерьер / Вельш Терьер'
Breed.create family: 'dog', title_en: 'Vizsla', title_ru: 'Венгерская короткошерстная легавая '
Breed.create family: 'dog', title_en: 'West_Highland_White_Terrier', title_ru: 'Вест хайленд уайт терьер'
Breed.create family: 'dog', title_en: 'Swedish_Vallhund', title_ru: 'Вестготашпиц/Шведский Валлхунд'
Breed.create family: 'dog', title_en: 'Westiepoo', title_ru: 'Вестипо '
Breed.create family: 'dog', title_en: 'Wolf_Hybrid', title_ru: 'Волкособ'
Breed.create family: 'dog', title_en: 'Glen_of_Imaal_Terrier', title_ru: 'Глен оф Имаал терьер'
Breed.create family: 'dog', title_en: 'Goldador', title_ru: 'Голдадор '
Breed.create family: 'dog', title_en: 'Goldendoodle', title_ru: 'Голдендудль'
Breed.create family: 'dog', title_en: 'Dutch_Shepherd', title_ru: 'Голландская овчарка'
Breed.create family: 'dog', title_en: 'Mountain_Cur', title_ru: 'Горная гончая'
Breed.create family: 'dog', title_en: 'Greyhound', title_ru: 'Грейхаунд '
Breed.create family: 'dog', title_en: 'Dalmatian', title_ru: 'Далматин'
Breed.create family: 'dog', title_en: 'Dandie_Dinmont_Terrier', title_ru: 'Денди динмонт терьер'
Breed.create family: 'dog', title_en: 'Jack_Russell_Terrier', title_ru: 'Джек Рассел терьер'
Breed.create family: 'dog', title_en: 'Jindo', title_ru: 'Джиндо'
Breed.create family: 'dog', title_en: 'Scottish_Deerhound', title_ru: 'Дирхаунд '
Breed.create family: 'dog', title_en: 'Doberman_Pinscher', title_ru: 'Доберман пинчер'
Breed.create family: 'dog', title_en: 'Doodleman_Pinscher', title_ru: 'Додлеман пинчер '
Breed.create family: 'dog', title_en: 'Treeing_Walker_Coonhound', title_ru: 'Древесная Енотовая Гончая Уолкера'
Breed.create family: 'dog', title_en: 'Treeing_Tennessee_Brindle', title_ru: 'Древесная Теннессийская Тигровая'
Breed.create family: 'dog', title_en: 'Black_Mouth_Cur', title_ru: 'Желтая с чеpной маской южная гончая'
Breed.create family: 'dog', title_en: 'Wirehaired_Pointing_Griffon', title_ru: 'Жесткошерстный пойнтер-гриффон '
Breed.create family: 'dog', title_en: 'Golden_Retriever', title_ru: 'Золотистый ретривер '
Breed.create family: 'dog', title_en: 'Ibizan_Hound', title_ru: 'Ивисская борзая'
Breed.create family: 'dog', title_en: 'Irish_Water_Spaniel', title_ru: 'Ирландский водяной спаниель'
Breed.create family: 'dog', title_en: 'Irish_Wolfhound', title_ru: 'Ирландский волкодав'
Breed.create family: 'dog', title_en: 'Irish_Setter', title_ru: 'Ирландский сеттер'
Breed.create family: 'dog', title_en: 'Irish_Terrier', title_ru: 'Ирландский терьер'
Breed.create family: 'dog', title_en: 'Icelandic_Sheepdog', title_ru: 'Исландская собака'
Breed.create family: 'dog', title_en: 'Italian_Spinone', title_ru: 'Итальянский спиноне'
Breed.create family: 'dog', title_en: 'Yorkshire_Terrier', title_ru: 'Йоркширский терьер'
Breed.create family: 'dog', title_en: 'Cavalier_King_Charles_Spaniel', title_ru: 'Кавалер Кинг Чарльз Спаниель '
Breed.create family: 'dog', title_en: 'Cavapoo', title_ru: 'Кавапу '
Breed.create family: 'dog', title_en: 'Cavachon', title_ru: 'Кавашон'
Breed.create family: 'dog', title_en: 'Caucasian_Mountain_Dog', title_ru: 'Кавказская овчарка'
Breed.create family: 'dog', title_en: 'Kai_Dog', title_ru: 'Каи'
Breed.create family: 'dog', title_en: 'Presa_Canario', title_ru: 'Канарская собака'
Breed.create family: 'dog', title_en: 'Cane_Corso_Mastiff', title_ru: 'Кане корсо или итальянский мастиф'
Breed.create family: 'dog', title_en: 'Karelian_Bear_Dog', title_ru: 'Карельская медвежья собака'
Breed.create family: 'dog', title_en: 'Poodle_Toy', title_ru: 'Карликовый пудель'
Breed.create family: 'dog', title_en: 'Carolina_Dog', title_ru: 'Каролинская Собака'
Breed.create family: 'dog', title_en: 'Cao_De_Castro_Laboreiro', title_ru: 'Каштро-лаборейрская собака'
Breed.create family: 'dog', title_en: 'Keeshond', title_ru: 'Кеесхонд / Вольфшпиц '
Breed.create family: 'dog', title_en: 'Cairn_Terrier', title_ru: 'Керн Терьер '
Breed.create family: 'dog', title_en: 'Cairnoodle', title_ru: 'Кернпу'
Breed.create family: 'dog', title_en: 'Kerry_Blue_Terrier', title_ru: 'Керри-блю терьер'
Breed.create family: 'dog', title_en: 'Chinese_Foo_Dog', title_ru: 'Китайская собака Фу'
Breed.create family: 'dog', title_en: 'Chinese_Chongqing_Dog', title_ru: 'Китайская собака Чунцина '
Breed.create family: 'dog', title_en: 'Chinese_Crested', title_ru: 'Китайская Хохлатая Собака'
Breed.create family: 'dog', title_en: 'Chinese_SharPei', title_ru: 'Китайский шар-пей'
Breed.create family: 'dog', title_en: 'Kishu_Ken', title_ru: 'Кишу-кен'
Breed.create family: 'dog', title_en: 'Clumber_Spaniel', title_ru: 'Кламбер спаниель'
Breed.create family: 'dog', title_en: 'Kooikerhondje', title_ru: 'Коикерхондье'
Breed.create family: 'dog', title_en: 'Cocker_Spaniel', title_ru: 'Кокер спаниель'
Breed.create family: 'dog', title_en: 'Cockapoo', title_ru: 'Кокер-пудель, кокапу, Кокерпудель'
Breed.create family: 'dog', title_en: 'Collie', title_ru: 'Колли'
Breed.create family: 'dog', title_en: 'Komondor', title_ru: 'Комондор'
Breed.create family: 'dog', title_en: 'Coton_De_Tulear', title_ru: 'Котон де тулеар'
Breed.create family: 'dog', title_en: 'Bluetick_Coonhound', title_ru: 'Крапчато-Голубой Кунхаунд'
Breed.create family: 'dog', title_en: 'Xoloitzcuintli', title_ru: 'Ксолоитцкуинтли'
Breed.create family: 'dog', title_en: 'Kuvasz', title_ru: 'Кувас'
Breed.create family: 'dog', title_en: 'German_Shorthaired_Pointer', title_ru: 'Курцхаар'
Breed.create family: 'dog', title_en: 'Curly_Coated_Retriever', title_ru: 'Курчавошерстный ретривер'
Breed.create family: 'dog', title_en: 'Labrador_Retriever', title_ru: 'Лабрадор ретривер'
Breed.create family: 'dog', title_en: 'Labradoodle', title_ru: 'Лабрадудл, или лабропудель'
Breed.create family: 'dog', title_en: 'Lagotto_Romagnolo', title_ru: 'Лаготто-романьоло'
Breed.create family: 'dog', title_en: 'Lancashire_Heeler', title_ru: 'Ланкашир хилер'
Breed.create family: 'dog', title_en: 'Italian_Greyhound', title_ru: 'Левретка '
Breed.create family: 'dog', title_en: 'Lakeland_Terrier', title_ru: 'Лейкленд Терьер'
Breed.create family: 'dog', title_en: 'Leonberger', title_ru: 'Леонбергер'
Breed.create family: 'dog', title_en: 'Catahoula_Leopard_Dog', title_ru: 'Леопардовая Собака Катахулы'
Breed.create family: 'dog', title_en: 'Lhasapoo', title_ru: 'Лхасопоо '
Breed.create family: 'dog', title_en: 'Lhasa_Apso', title_ru: 'Лхасский апсо'
Breed.create family: 'dog', title_en: 'McNab', title_ru: 'МакНаб '
Breed.create family: 'dog', title_en: 'Malshi', title_ru: 'Мал-ши'
Breed.create family: 'dog', title_en: 'Petit_Basset_Griffon_Vendeen', title_ru: 'Малый Вандейский Бассет Гриффон'
Breed.create family: 'dog', title_en: 'Maltese', title_ru: 'Мальтийская болонка'
Breed.create family: 'dog', title_en: 'Maltipom', title_ru: 'Мальтипом'
Breed.create family: 'dog', title_en: 'Maltipoo', title_ru: 'Мальтипу'
Breed.create family: 'dog', title_en: 'Manchester_Terrier', title_ru: 'Манчестерский терьер'
Breed.create family: 'dog', title_en: 'Manchester_Terrier_Toy', title_ru: 'Манчестерский той-терьер'
Breed.create family: 'dog', title_en: 'Maremma_Sheepdog', title_ru: 'Маремма '
Breed.create family: 'dog', title_en: 'Neapolitan_Mastiff', title_ru: 'Мастино Наполетано / Неаполитанский Мастиф'
Breed.create family: 'dog', title_en: 'Mastiff', title_ru: 'Мастиф'
Breed.create family: 'dog', title_en: 'Miniature_Australian_Shepherd', title_ru: 'Миниатюрная австралийская овчарка'
Breed.create family: 'dog', title_en: 'Miniature_Bull_Terrier', title_ru: 'Миниатюрный бультерьер'
Breed.create family: 'dog', title_en: 'Schnauzer_Standard', title_ru: 'Миттельшнауцер'
Breed.create family: 'dog', title_en: 'Pug', title_ru: 'Мопс'
Breed.create family: 'dog', title_en: 'Morkie', title_ru: 'Морки / Йорктиз'
Breed.create family: 'dog', title_en: 'Mudi', title_ru: 'Муди'
Breed.create family: 'dog', title_en: 'Soft_Coated_Wheaten_Terrier', title_ru: 'Мягкошерстный пшеничный терьер'
Breed.create family: 'dog', title_en: 'German_Shepherd', title_ru: 'Немецкая овчарка'
Breed.create family: 'dog', title_en: 'Great_Dane', title_ru: 'Немецкий дог'
Breed.create family: 'dog', title_en: 'German_Wirehaired_Pointer', title_ru: 'Немецкий жесткошерстный пойнтер '
Breed.create family: 'dog', title_en: 'German_Pinscher', title_ru: 'Немецкий пинчер'
Breed.create family: 'dog', title_en: 'New_Guinea_Singing_Dog', title_ru: 'Новогвинейская поющая собака'
Breed.create family: 'dog', title_en: 'Nova_Scotia_Duck_Tolling_Retriever', title_ru: 'Новошотландский утиный ретривер'
Breed.create family: 'dog', title_en: 'Norwegian_Buhund', title_ru: 'Норвежский бухунд '
Breed.create family: 'dog', title_en: 'Norwegian_Lundehund', title_ru: 'Норвежский лундехунд '
Breed.create family: 'dog', title_en: 'Norwegian_Elkhound', title_ru: 'Норвежский элкхаунд '
Breed.create family: 'dog', title_en: 'Norwich_Terrier', title_ru: 'Норвич Терьер'
Breed.create family: 'dog', title_en: 'Norfolk_Terrier', title_ru: 'Норфолк Терьер'
Breed.create family: 'dog', title_en: 'Newfoundland', title_ru: 'Ньюфаундленд'
Breed.create family: 'dog', title_en: 'Polish_Tatra_Sheepdog', title_ru: 'Овчарка польская подгалянская'
Breed.create family: 'dog', title_en: 'Otterhound', title_ru: 'Оттерхаунд '
Breed.create family: 'dog', title_en: 'Papillon', title_ru: 'Папильон '
Breed.create family: 'dog', title_en: 'Papoo', title_ru: 'Папоо '
Breed.create family: 'dog', title_en: 'Parson_Russell_Terrier', title_ru: 'Парсон Рассел терьер'
Breed.create family: 'dog', title_en: 'Patterdale_Terrier', title_ru: 'Паттердейл Терьер'
Breed.create family: 'dog', title_en: 'Pekingese', title_ru: 'Пекинес'
Breed.create family: 'dog', title_en: 'Peruvian_Inca_Orchid', title_ru: 'Перуанская орхидея инков'
Breed.create family: 'dog', title_en: 'Lowchen', title_ru: 'Петит Шьен Лион / Малая львиная собака'
Breed.create family: 'dog', title_en: 'Peek_A_Pom', title_ru: 'Пикапом'
Breed.create family: 'dog', title_en: 'Pekepoo', title_ru: 'Пикапу'
Breed.create family: 'dog', title_en: 'Berger_Picard', title_ru: 'Пикардийская Овчарка'
Breed.create family: 'dog', title_en: 'Great_Pyrenees', title_ru: 'Пиренейская горная собака'
Breed.create family: 'dog', title_en: 'Pyrenean_Shepherd', title_ru: 'Пиренейская овчарка '
Breed.create family: 'dog', title_en: 'Pyrenean_Mastiff', title_ru: 'Пиренейский мастиф'
Breed.create family: 'dog', title_en: 'Plott_Hound', title_ru: 'Плоттхаунд '
Breed.create family: 'dog', title_en: 'Pointer', title_ru: 'Пойнтер'
Breed.create family: 'dog', title_en: 'Polish_Lowland_Sheepdog', title_ru: 'Польская низинная овчарка'
Breed.create family: 'dog', title_en: 'Pomapoo', title_ru: 'Помапу'
Breed.create family: 'dog', title_en: 'Pomeranian', title_ru: 'Померанский шпиц '
Breed.create family: 'dog', title_en: 'Pomchi', title_ru: 'Помчи'
Breed.create family: 'dog', title_en: 'Portuguese_Water_Dog', title_ru: 'Португальская водяная собака'
Breed.create family: 'dog', title_en: 'Portuguese_Podengo', title_ru: 'Португальский поденгу'
Breed.create family: 'dog', title_en: 'Portuguese_Pointer', title_ru: 'Португальский Пойнтер'
Breed.create family: 'dog', title_en: 'Flat_Coated_Retriever', title_ru: 'Прямошерстный ретривер'
Breed.create family: 'dog', title_en: 'Puggle', title_ru: 'Пугль или Пагль'
Breed.create family: 'dog', title_en: 'Poodle_Standard', title_ru: 'Пудель'
Breed.create family: 'dog', title_en: 'Puli', title_ru: 'Пули'
Breed.create family: 'dog', title_en: 'Pumi', title_ru: 'Пуми'
Breed.create family: 'dog', title_en: 'Rafeiro_do_Alentejo', title_ru: 'Рафейро До Алентейо / Португальская Сторожевая'
Breed.create family: 'dog', title_en: 'Redbone_Coonhound', title_ru: 'Редбон Кунхаунд - красная собака'
Breed.create family: 'dog', title_en: 'Schnauzer_Giant', title_ru: 'Ризеншнауцер '
Breed.create family: 'dog', title_en: 'Rhodesian_Ridgeback', title_ru: 'Родезийский риджбек'
Breed.create family: 'dog', title_en: 'Rottweiler', title_ru: 'Ротвейлер'
Breed.create family: 'dog', title_en: 'Black_Russian_Terrier', title_ru: 'Русский черный терьер'
Breed.create family: 'dog', title_en: 'Rat_Terrier', title_ru: 'Рэт-терьер '
Breed.create family: 'dog', title_en: 'Saint_Berdoodle', title_ru: 'Сайнт Бердудль '
Breed.create family: 'dog', title_en: 'Saluki', title_ru: 'Салюки '
Breed.create family: 'dog', title_en: 'Samoyed', title_ru: 'Самоед, Самоедская лайка'
Breed.create family: 'dog', title_en: 'Saint_Bernard', title_ru: 'Сенбернар'
Breed.create family: 'dog', title_en: 'Gordon_Setter', title_ru: 'Сеттер-гордон '
Breed.create family: 'dog', title_en: 'Siberian_Husky', title_ru: 'Сибирский хаски'
Breed.create family: 'dog', title_en: 'Sealyham_Terrier', title_ru: 'Силихем-терьер'
Breed.create family: 'dog', title_en: 'Skye_Terrier', title_ru: 'Скай терьер'
Breed.create family: 'dog', title_en: 'Scottish_Terrier', title_ru: 'Скотчтерьер '
Breed.create family: 'dog', title_en: 'Sloughi', title_ru: 'Слюги '
Breed.create family: 'dog', title_en: 'Central_Asian_Ovtcharka', title_ru: 'Среднеазиатская овчарка'
Breed.create family: 'dog', title_en: 'Stabyhoun', title_ru: 'Стабихун'
Breed.create family: 'dog', title_en: 'Olde_English_Sheepdog', title_ru: 'Староанглийская овчарка '
Breed.create family: 'dog', title_en: 'Olde_English_Bulldogge', title_ru: 'Староанглийский бульдог'
Breed.create family: 'dog', title_en: 'Staffordshire_Bull_Terrier', title_ru: 'Стаффордширский бультерьер'
Breed.create family: 'dog', title_en: 'Sussex_Spaniel', title_ru: 'Суссекс Спаниель'
Breed.create family: 'dog', title_en: 'Schapendoes', title_ru: 'Схапендус '
Breed.create family: 'dog', title_en: 'Thai_Ridgeback', title_ru: 'Тайский риджбек'
Breed.create family: 'dog', title_en: 'Dachshund', title_ru: 'Такса'
Breed.create family: 'dog', title_en: 'Tibetan_Mastiff', title_ru: 'Тибетский мастиф'
Breed.create family: 'dog', title_en: 'Tibetan_Spaniel', title_ru: 'Тибетский спаниель'
Breed.create family: 'dog', title_en: 'Tibetan_Terrier', title_ru: 'Тибетский терьер'
Breed.create family: 'dog', title_en: 'Fox_Terrier_Toy', title_ru: 'Той Фокстерьер'
Breed.create family: 'dog', title_en: 'Tosa_Inu', title_ru: 'Тоса-ину '
Breed.create family: 'dog', title_en: 'Whippet', title_ru: 'Уиппет'
Breed.create family: 'dog', title_en: 'Whoodles', title_ru: 'Уодлес '
Breed.create family: 'dog', title_en: 'Pharaoh_Hound', title_ru: 'Фараонова собака'
Breed.create family: 'dog', title_en: 'Fila_Brasileiro', title_ru: 'Фила Бразилейру'
Breed.create family: 'dog', title_en: 'Field_Spaniel', title_ru: 'Филд-спаниель'
Breed.create family: 'dog', title_en: 'Finnish_Lapphund', title_ru: 'Финский лаппхунд'
Breed.create family: 'dog', title_en: 'Finnish_Spitz', title_ru: 'Финский шпиц '
Breed.create family: 'dog', title_en: 'Fox_Terrier_Smooth', title_ru: 'Фокстерьер гладкошерстный'
Breed.create family: 'dog', title_en: 'Fox_Terrier_Wire', title_ru: 'Фокстерьер Жесткошерстный'
Breed.create family: 'dog', title_en: 'French_Bulldog', title_ru: 'Французский бульдог'
Breed.create family: 'dog', title_en: 'Havanese', title_ru: 'Хаванез'
Breed.create family: 'dog', title_en: 'Canaan_Dog', title_ru: 'Ханаанская собака'
Breed.create family: 'dog', title_en: 'Harrier', title_ru: 'Харьер'
Breed.create family: 'dog', title_en: 'German_Hovawart', title_ru: 'Ховаварт'
Breed.create family: 'dog', title_en: 'Miniature_Pinscher', title_ru: 'Цвергпинчер / Карликовый пинчер / Миниатюрный пинчер'
Breed.create family: 'dog', title_en: 'Schnauzer_Miniature', title_ru: 'Цвергшнауцер'
Breed.create family: 'dog', title_en: 'Chow_Chow', title_ru: 'Чау-чау'
Breed.create family: 'dog', title_en: 'Black_and_Tan_Coonhound', title_ru: 'Черно-подпалый кунхаунд / Енотовая собака'
Breed.create family: 'dog', title_en: 'Chesapeake_Bay_Retriever', title_ru: 'Чесапик Бей Ретривер'
Breed.create family: 'dog', title_en: 'Czechoslovakian_Wolfdog', title_ru: 'Чешский вольфхунд'
Breed.create family: 'dog', title_en: 'Cesky_Terrier', title_ru: 'Чешский терьер'
Breed.create family: 'dog', title_en: 'Chinook', title_ru: 'Чинук'
Breed.create family: 'dog', title_en: 'Cirneco_dell_Etna', title_ru: 'Чирнеко Дель Этна'
Breed.create family: 'dog', title_en: 'Chihuahua', title_ru: 'Чихуахуа'
Breed.create family: 'dog', title_en: 'Chipoo', title_ru: 'Чихуахуа / Пудель микс'
Breed.create family: 'dog', title_en: 'Illyrian_Sheepdog', title_ru: 'Шарпланинак / Югославская Овчарка'
Breed.create family: 'dog', title_en: 'Sheltie', title_ru: 'Шелти '
Breed.create family: 'dog', title_en: 'Shepadoodle', title_ru: 'Шепадудль'
Breed.create family: 'dog', title_en: 'Shih_Tzu', title_ru: 'Ши-тцу'
Breed.create family: 'dog', title_en: 'Shiba_Inu', title_ru: 'Шиба-ину'
Breed.create family: 'dog', title_en: 'Shiloh_Shepherd', title_ru: 'Шилонская овчарка'
Breed.create family: 'dog', title_en: 'Schipperke', title_ru: 'Шипперке'
Breed.create family: 'dog', title_en: 'Shihpoo', title_ru: 'Шихпу'
Breed.create family: 'dog', title_en: 'Schnoodle', title_ru: 'Шнудле'
Breed.create family: 'dog', title_en: 'Entlebucher_Mountain_Dog', title_ru: 'Энтлебухер Зенненхунд'
Breed.create family: 'dog', title_en: 'Airedale_Terrier', title_ru: 'Эрдельтерьер'
Breed.create family: 'dog', title_en: 'Eskapoo', title_ru: 'Эскапу '
Breed.create family: 'dog', title_en: 'Eskimo_Dog', title_ru: 'Эскимосская собака'
Breed.create family: 'dog', title_en: 'Estrela_Mountain_Dog', title_ru: 'Эштрельская овчарка'
Breed.create family: 'dog', title_en: 'South_African_Boerboel', title_ru: 'Южноафриканский бурбуль'
Breed.create family: 'dog', title_en: 'South_Russian_Ovcharka', title_ru: 'Южнорусская овчарка'
Breed.create family: 'dog', title_en: 'Hunt_Terrier', title_ru: 'Ягдтерьер'
Breed.create family: 'dog', title_en: 'Japanese_Chin', title_ru: 'Японский хин'